<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function grnbth_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
    'type' => 'grnbth_holder',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1385069092',
    'changed' => '1385069743',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'revision_uid' => '1',
    'title' => 'Water Saving',
    'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suam denique cuique naturam esse ad vivendum ducem. Aeque enim contingit omnibus fidibus, ut incontentae sint. Aperiendum est igitur, quid sit voluptas; Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Ita credo. An potest, inquit ille, quicquam esse suavius quam nihil dolere? Duo Reges: constructio interrete. Vide, ne etiam menses! nisi forte eum dicis, qui, simul atque arripuit, interficit.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suam denique cuique naturam esse ad vivendum ducem. Aeque enim contingit omnibus fidibus, ut incontentae sint. Aperiendum est igitur, quid sit voluptas; Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Ita credo. An potest, inquit ille, quicquam esse suavius quam nihil dolere? Duo Reges: constructio interrete. Vide, ne etiam menses! nisi forte eum dicis, qui, simul atque arripuit, interficit.</p>
  ',
    'teaser' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suam denique cuique naturam esse ad vivendum ducem. Aeque enim contingit omnibus fidibus, ut incontentae sint. Aperiendum est igitur, quid sit voluptas; Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Ita credo. An potest, inquit ille, quicquam esse suavius quam nihil dolere? Duo Reges: constructio interrete. Vide, ne etiam menses! nisi forte eum dicis, qui, simul atque arripuit, interficit.</p>',
    'log' => '',
    'revision_timestamp' => '1385069743',
    'format' => '2',
    'name' => 'ChrisChinchilla',
    'picture' => 'sites/default/files/pictures/picture-1.jpg',
    'data' => 'a:10:{s:18:"admin_compact_mode";b:0;s:8:"new_role";i:0;s:12:"new_role_add";s:1:"3";s:16:"new_role_add_qty";s:0:"";s:24:"new_role_add_granularity";s:3:"day";s:7:"contact";i:1;s:13:"form_build_id";s:37:"form-adcba416485286c296675d5d385f4de7";s:14:"picture_delete";i:0;s:14:"picture_upload";s:0:"";s:5:"block";a:1:{s:10:"masquerade";a:1:{i:0;i:1;}}}',
    'path' => 'watersaving',
    'field_wysiwyg_images' => array(),
    'last_comment_timestamp' => '1385069092',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'files' => array(),
    '0' => FALSE,
    'probability' => 100,
    'page_title' => '',
    'uuid' => 'cc20ac70-52f9-11e3-ad50-003048612c9c',
    'revision_uuid' => 'cc21acb4-52f9-11e3-ad50-003048612c9c',
    'nodewords' => array(
      'abstract' => array(
        'value' => '',
      ),
      'canonical' => array(
        'value' => '',
        'hide' => 0,
      ),
      'copyright' => array(
        'value' => '',
      ),
      'dcterms.contributor' => array(
        'value' => '',
      ),
      'dcterms.creator' => array(
        'value' => '',
        'auto' => 0,
      ),
      'dcterms.date' => array(
        'value' => array(
          'day' => '22',
          'month' => '11',
          'year' => '2013',
        ),
      ),
      'dcterms.description' => array(
        'value' => '',
      ),
      'dcterms.title' => array(
        'value' => '',
      ),
      'description' => array(
        'value' => '',
      ),
      'geo.placename' => array(
        'value' => '',
      ),
      'geo.region' => array(
        'value' => '',
      ),
      'keywords' => array(
        'value' => '',
      ),
      'location' => array(
        'latitude' => '',
        'longitude' => '',
      ),
      'original-source' => array(
        'value' => '',
      ),
      'page_title' => array(
        'value' => '',
        'append' => 1,
        'divider' => ' | ',
      ),
      'revisit-after' => array(
        'value' => '',
      ),
      'robots' => array(
        'value' => array(
          'index' => 0,
          'noindex' => 0,
          'follow' => 0,
          'nofollow' => 0,
          'noarchive' => 0,
          'noodp' => 0,
          'nosnippet' => 0,
          'noydir' => 0,
        ),
        'use_default' => 0,
      ),
      'shorturl' => array(
        'value' => '',
      ),
      'standout' => array(
        'value' => '',
      ),
      'syndication-source' => array(
        'value' => '',
      ),
    ),
    'pathauto_perform_alias' => FALSE,
    'date' => '2013-11-22 08:24:52 +1100',
  );
  return $nodes;
}
