<?php

DEFINE('DRUPALMONITOR_VERSION', '6.1.9');

include('drupalmonitor.user.inc');
include('drupalmonitor.files.inc');
include('drupalmonitor.load.inc');
include('drupalmonitor.watchdog.inc');
include('drupalmonitor.status.inc');
include('drupalmonitor.node.inc');

function drupalmonitor_menu() {
  $items = array();
  $items['drupalmonitor'] = array(
    'title' => 'Drupal Monitor',
    'page callback' => 'drupalmonitor_page_data',
    'access arguments' => array('access content'),
  );
  $items['admin/settings/drupalmonitor'] = array(
    'title' => 'Drupalmonitor.com Settings',
    'page callback' => 'drupalmonitor_page_settings',
    'access arguments' => array('administer drupalmonitor'),
  );
  return $items;
}

function drupalmonitor_perm() {
  return array('administer drupalmonitor');
}

function drupalmonitor_page_settings() {
  $output .= drupal_get_form('drupalmonitor_settings_form');
  return $output;
}

function drupalmonitor_settings_form() {
  $form['drupalmonitor_hash'] = array(
    '#type' => 'textfield',
    '#title' => t('Drupalmonitor.com Website Security Hash'),
    '#default_value' => variable_get('drupalmonitor_hash', ''),
    '#size' => 60,
    '#maxlength' => 64,
    '#description' => t('This hash should be the same string as in your site settings on <a href="http://www.drupalmonitor.com/websites" target="_blank">drupalmonitor.com/websites</a>.'),
  );
  
  $form['drupalmonitor_memory_monitoring'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Drupalmonitor.com Logging'),
    '#default_value' => variable_get('drupalmonitor_memory_monitoring', ''),
    '#size' => 60,
    '#maxlength' => 64,
    '#description' => t('Enable or disable performance logging. If enabled, the drupalmonitor.com module will log all page requests on your Drupal site. Logs are needed to generate load graphs on <a href="http://www.drupalmonitor.com/websites" target="_blank">drupalmonitor.com/websites</a>. On high traffic websites, logging can be time consuming and slow your website.'),
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}


function drupalmonitor_settings_form_submit($form, &$form_state) {
  variable_set('drupalmonitor_hash', $form_state['values']['drupalmonitor_hash']);
  variable_set('drupalmonitor_memory_monitoring', $form_state['values']['drupalmonitor_memory_monitoring']);
  drupal_set_message(t('Drupalmonitor.com settings saved.'));
}

function drupalmonitor_drupalmonitor() {
  $data['files'] = array('count'=>'10');
  return $data;
}

function drupalmonitor_page_data() {

  $starttime = microtime();

  $hash_site = variable_get('drupalmonitor_hash', '');
  $hash_request = $_GET['hash'];

  if ($hash_site == '' || $hash_site == $hash_request) {
  
    header("Pragma: no-cache");
    header("Expires: 0");
  
    // User Count Data
    $info['user_usercount'] = drupalmonitor_get_user_usercount();
    $info['user_activesessioncount_300s'] = drupalmonitor_get_user_activesessioncount_300s();
    $info['user_loggedinsessioncount_300s'] = drupalmonitor_get_user_loggedinsessioncount_300s();
  
    // Files Count Data
    $info['files_filescount'] = drupalmonitor_get_files_filescount();
    $info['files_filesfoldersize'] = drupalmonitor_get_files_filesfoldersize();
  
    // Load Cound Data
    $info['load_requestscount_300s'] = drupalmonitor_get_load_requestscount_300s();
    $info['load_requestspersecondcount_300s'] = drupalmonitor_get_load_requestspersecondcount_300s();
    $info['load_slowrequestscount_300s'] = drupalmonitor_get_load_slowrequestscount_300s();
    $info['load_slowrequests_300s'] = drupalmonitor_get_load_slowrequests_300s();
    $info['load_maxmemoryusage'] = drupalmonitor_get_load_maxmemoryusage();
    $info['load_apcenabled'] = drupalmonitor_load_apcenabled();

    // Watchdog Counts
    $info['drupalmonitor_get_watchdog_pagenotfoundcount_300s'] = drupalmonitor_get_watchdog_pagenotfoundcount_300s();
    $info['drupalmonitor_get_watchdog_user_300s'] = drupalmonitor_get_watchdog_user_300s();
    $info['drupalmonitor_get_watchdog_accessdenied_300s'] = drupalmonitor_get_watchdog_accessdenied_300s();
    $info['drupalmonitor_get_watchdog_mail_300s'] = drupalmonitor_get_watchdog_mail_300s();
    $info['drupalmonitor_get_watchdog_search_300s'] = drupalmonitor_get_watchdog_search_300s();
    $info['drupalmonitor_get_watchdog_php_300s'] = drupalmonitor_get_watchdog_php_300s();
    $info['drupalmonitor_get_watchdog_content_300s'] = drupalmonitor_get_watchdog_content_300s();
  
    // Watchdog Contenttypes
    $info['drupalmonitor_node_contenttypes'] = drupalmonitor_node_contenttypes();
  
    // Drupal Status
    //$info['drupalmonitor_status_listmodules'] = drupalmonitor_status_listmodules();
    $info['tbl_system'] = drupalmonitor_status_listmodules();
    $info['drupalmonitor_status_checkunwantedfiles'] = drupalmonitor_status_checkunwantedfiles();
    $info['tbl_variable'] = drupalmonitor_status_listvars();

    // Call hook_drupalmonitor()
    $info['custom'] = module_invoke_all('drupalmonitor');
    
    // Drupal Stats
    $info['variables']['page_compression'] = variable_get('page_compression', 0);
    $info['variables']['update_last_check'] = variable_get('update_last_check', 0);
    $info['variables']['cron_last']  = variable_get('cron_last', 0);
    $info['variables']['update_check_frequency'] = variable_get('update_check_frequency', 1);
    $info['variables']['block_cache'] = variable_get('block_cache', 0);
    $info['variables']['cache'] = variable_get('cache', 0);
    $info['variables']['preprocess_css'] = variable_get('preprocess_css', 0);
    $info['variables']['preprocess_js'] = variable_get('preprocess_js', 0);
    $info['variables']['page_compression'] = variable_get('page_compression', 0);
    $info['variables']['clean_url'] = variable_get('clean_url', 0);
    $info['variables']['install_profile'] = variable_get('install_profile', 0);
    $info['variables']['site_mail'] = variable_get('site_mail', 0);
    $info['variables']['update_last_check'] = variable_get('update_last_check', 0);
    $info['variables']['site_403'] = variable_get('site_403', 0);
  
    // Drupalmonitor infos
    $info['drupalmonitor_version'] = DRUPALMONITOR_VERSION;
    $info['drupalmonitor_executiontime'] = microtime() - $starttime;
    $info['drupalmonitor_status'] = "OK";
  } else {
    $info['drupalmonitor_status'] = "NO ACCESS";
  }
  
  $json_data = json_encode($info);
  echo $json_data;
  exit();
}


/**
 * take time on init
 *
 * @param n/a
 * @return n/a
 */
function drupalmonitor_init() {
  global $script_start_time;
  $script_start_time = microtime(true);
}

/**
 * take time on exit and save to db
 *
 * @param n/a
 * @return n/a
 */
function drupalmonitor_exit() {
  global $script_start_time;
  if(variable_get('drupalmonitor_memory_monitoring', 1) == 1) {
    $diff = round(((microtime(true)-$script_start_time)*1000));
    
    if($diff < 2147483648) {    
      $data = array(
       'q'=>$_GET['q'],
       'memory'=>memory_get_peak_usage(),
       'dt'=>time(),
       'execution_time'=>$diff
      );
      // we can't use db_insert as that isn't reliably loaded in hook_exit() 
      db_query("INSERT INTO {drupalmonitor_log} (q,memory,dt,execution_time) VALUES ('%s',%d,%d,%d)", $data['q'],$data['memory'],$data['dt'],$data['execution_time']);
    }
  }
}



function drupalmonitor_cron() {
  //remove old entries
  $offset = time() - 60*15; //15 Minuten
  $sql = "DELETE FROM drupalmonitor_log WHERE dt < " . $offset;
  db_query($sql);

  // ping drupalmonitor.com when cron is called
  $request_url = 'http://www.drupalmonitor.com/pingback';
  $request_headers = array('Content-Type' => 'application/x-www-form-urlencoded');
  $request_method = 'POST';
  $request_retry = 3;
  $data = 'DRUPALMONITOR_VERSION='.DRUPALMONITOR_VERSION.'&SERVER_NAME='.$_SERVER['SERVER_NAME'].'&SERVER_ADDR='.$_SERVER['SERVER_ADDR'];
  $result = drupal_http_request($request_url, $request_headers, $request_method, $data, $request_retry);
}

