<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function eco_challenge_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_node_info().
 */
function eco_challenge_node_info() {
  $items = array(
    'ec_blog' => array(
      'name' => t('Eco Challenge blog'),
      'module' => 'features',
      'description' => t('Have you got updates and news to share on challenges you\'ve taken part in?'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'min_word_count' => '0',
      'help' => '',
    ),
    'ec_event' => array(
      'name' => t('Eco Challenge event'),
      'module' => 'features',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'min_word_count' => '0',
      'help' => '',
    ),
    'ec_group' => array(
      'name' => t('Eco Challenge group'),
      'module' => 'features',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'min_word_count' => '0',
      'help' => '',
    ),
    'ecochallenge' => array(
      'name' => t('Eco Challenge'),
      'module' => 'features',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'min_word_count' => '0',
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implementation of hook_views_api().
 */
function eco_challenge_views_api() {
  return array(
    'api' => '3.0',
  );
}
