<?php

function uc_autocalc_shipping_form_alter(&$form,$form_state,$form_id){
  if ('uc_cart_checkout_form' == $form_id){
    drupal_add_js('$(document).ready(function(){
    
    	$("#quotes-pane legend a").text("Shipping cost");
    
    	var shipping_button = $("input#edit-panes-quotes-quote-button");
    	shipping_button.hide();
    	
    	// click button when country is changed
    	var selected_country = $("#edit-panes-delivery-delivery-country");
    	selected_country.change(function(){
    		shipping_button.click();
  		});
    	 
    	// if country already selected then click the button
    	if (undefined != selected_country.val())
    		shipping_button.click();

    });', 'inline');
  }
}

