<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function press_area_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
    'type' => 'page',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1375332507',
    'changed' => '1375336276',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'revision_uid' => '1',
    'title' => 'Press',
    'body' => '<p>One of our aims is to ensure that renters are included in conversations around sustainability and housing more generally, we are often asked for our thoughts and opinions by the media and below is a selection of some of our appearances.</p>
    ',
    'teaser' => '<p>One of our aims is to ensure that renters are included in conversations around sustainability and housing more generally, we are often asked for our thoughts and opinions by the media and below is a selection of some of our appearances.</p>
    ',
    'log' => '',
    'revision_timestamp' => '1375336276',
    'format' => '2',
    'name' => 'ChrisChinchilla',
    'picture' => 'sites/default/files/pictures/picture-1.jpg',
    'data' => 'a:10:{s:18:"admin_compact_mode";b:0;s:8:"new_role";i:0;s:12:"new_role_add";s:1:"3";s:16:"new_role_add_qty";s:0:"";s:24:"new_role_add_granularity";s:3:"day";s:7:"contact";i:1;s:13:"form_build_id";s:37:"form-adcba416485286c296675d5d385f4de7";s:14:"picture_delete";i:0;s:14:"picture_upload";s:0:"";s:5:"block";a:1:{s:10:"masquerade";a:1:{i:0;i:1;}}}',
    'field_image' => array(),
    'field_wysiwyg_images' => array(),
    'webform' => array(
      'confirmation' => '',
      'confirmation_format' => '2',
      'redirect_url' => '<confirmation>',
      'teaser' => '0',
      'block' => '0',
      'allow_draft' => '0',
      'auto_save' => '0',
      'submit_notice' => '1',
      'submit_text' => '',
      'submit_limit' => '-1',
      'submit_interval' => '-1',
      'total_submit_limit' => '-1',
      'total_submit_interval' => '-1',
      'status' => '1',
      'record_exists' => FALSE,
      'roles' => array(
        '0' => '1',
        '1' => '2',
      ),
      'emails' => array(),
      'components' => array(),
    ),
    'last_comment_timestamp' => '1375336130',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'files' => array(),
    '0' => FALSE,
    'probability' => 100,
    'page_title' => '',
    'uuid' => '9af12fa0-fa65-11e2-b079-45cf3fcc45f4',
    'revision_uuid' => '61525c8b-fa6e-11e2-9e36-003048612c9c',
    'nodewords' => array(
      'abstract' => array(
        'value' => '',
      ),
      'canonical' => array(
        'value' => '',
        'hide' => 0,
      ),
      'copyright' => array(
        'value' => '',
      ),
      'dcterms.contributor' => array(
        'value' => '',
      ),
      'dcterms.creator' => array(
        'value' => '',
        'auto' => 0,
      ),
      'dcterms.date' => array(
        'value' => array(
          'day' => '1',
          'month' => '8',
          'year' => '2013',
        ),
      ),
      'dcterms.description' => array(
        'value' => '',
      ),
      'dcterms.title' => array(
        'value' => '',
      ),
      'description' => array(
        'value' => '',
      ),
      'geo.placename' => array(
        'value' => '',
      ),
      'geo.region' => array(
        'value' => '',
      ),
      'keywords' => array(
        'value' => '',
      ),
      'location' => array(
        'latitude' => '',
        'longitude' => '',
      ),
      'original-source' => array(
        'value' => '',
      ),
      'page_title' => array(
        'value' => '',
        'append' => 1,
        'divider' => ' | ',
      ),
      'revisit-after' => array(
        'value' => '',
      ),
      'robots' => array(
        'value' => array(
          'index' => 0,
          'noindex' => 0,
          'follow' => 0,
          'nofollow' => 0,
          'noarchive' => 0,
          'noodp' => 0,
          'nosnippet' => 0,
          'noydir' => 0,
        ),
        'use_default' => 0,
      ),
      'shorturl' => array(
        'value' => '',
      ),
      'standout' => array(
        'value' => '',
      ),
      'syndication-source' => array(
        'value' => '',
      ),
    ),
    'date' => '2013-08-01 14:48:27 +1000',
  );
  return $nodes;
}
