<?php
/**
 * @file
 * Drupal module file for civicrm_activity_ical
 *
 */

require_once drupal_get_path('module', 'civicrm_activity_ical') .'/functions.php';
require_once drupal_get_path('module', 'civicrm_activity_ical') .'/civi_hooks.php';

/**
 * Implements hook_block().
 */
function civicrm_activity_ical_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['quick_links'] = array(
        'info' => t('CiviCRM activity iCal links'),
        'cache' => BLOCK_CACHE_PER_USER,
      );

      return $blocks;
      break;
    case 'view':
      $block = array();
      switch ($delta) {
        case 'quick_links':
          $block['subject'] = t('CiviCRM activity iCal links');
          $block['content'] = theme('civicrm_activity_ical_quick_links');
          break;
      }
      return $block;
      break;
  }
}

/**
 * Implements hook_theme()
 */
function civicrm_activity_ical_theme($existing, $type, $theme, $path) {
  $items = array(
    'civicrm_activity_ical_quick_links' => array(
      'arguments' => array(),
    ),
  );
  return $items;
}

/**
 * Implements hook_menu().
 */
function civicrm_activity_ical_menu() {
  $items['civicrm_activity_ical/settings/user'] = array(
    'title' => 'CiviCRM activities iCal feed',
    'type' => MENU_CALLBACK,
    'page callback' => 'civicrm_activity_ical_user_page',
    'access arguments' => array('access CiviCRM activity iCalendar feed'),
  );
  $items['civicrm_activity_ical/feed/%/%'] = array(
    'title' => 'CiviCRM activities iCal feed',
    'type' => MENU_CALLBACK,
    'page callback' => 'civicrm_activity_ical_view_feed',
    'page arguments' => array(2, 3),
    'access callback' => 'civicrm_activity_ical_feed_access',
    'access arguments' => array(2),
  );
  $items['admin/settings/civicrm_activity_ical'] = array(
    'title' => 'CiviCRM activities iCal feed settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('civicrm_activity_ical_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implements hook_perm()
 */
function civicrm_activity_ical_perm() {
  $perms = array(
    'access CiviCRM activity iCalendar feed',
  );
  return $perms;
}

/**
 * Implements hook_help().
 */
function civicrm_activity_ical_help($path, $arg) {
  switch ($path) {
    case 'admin/help#civicrm_activity_ical':
      // Return a line-break version of the module README.txt
      return filter_filter('process', 1, NULL, file_get_contents( dirname(__FILE__) . "/README.txt") );
      break;
  }
}

/**
 * Implements hook_enable().
 */
function civicrm_activity_ical_enable() {
  $params = array(
    '!link' => l('Administer > Site configuration > CiviCRM activities iCalendar feed',  'admin/settings/civicrm_activity_ical' ),
    );
  drupal_set_message(t("CiviCRM activity iCalendar feed settings are available at !link", $params));
}
